services:
  # Node.js Application Service
  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: pricing-api
    volumes:
      - ./api:/app
      - ./api/node_modules:/app/node_modules
    working_dir: /app
    ports:
      - "8001:8001"
    stdin_open: true
    tty: true
    depends_on:
      - db

  # PostgreSQL Database Service
  db:
    image: postgres:13-alpine
    container_name: pricing-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pricing_db
    ports:
      - "5432:5432" # Map PostgreSQL port
    volumes:
      - pricing_db_data:/var/lib/postgresql/data # Persist data
      - ./api/src/infrastructure/init/create_test_db.sql:/docker-entrypoint-initdb.d/create_test_db.sql

volumes:
  pricing_db_data:
    driver: local
