# Use official Node.js image (Alpine for smaller size)
FROM node:18-alpine

# Set working directory inside the container
WORKDIR /app

# Copy all files into the container
COPY . .

# Keep the container running
CMD ["sh"]
